#' Title
#'
#' @inheritParams create_presentation
#'
#' @return A list of roxygen2 properties for the package's DESCRIPTION file used
#'   to create the title slide
#' @keywords internal
.get_title <- function(package) {
  lib <- .get_desc(package, "Package")
  version <- .get_desc(package, "Version")

  title_details <- list(
    "lib" = lib,
    "version" = version
  )
  return(title_details)
}

#' Title
#'
#' @param package_details A list of function details from `.get_title`
#' @param yaml A list of properties from `.parse_yaml()`
#'
#' @return A character vector of properties formatted for writing to a file
#' @keywords internal
.collate_title <- function(title_details, yaml) {
  title_contents <- glue::glue(
    "% Generated by pkgslides: do not edit by hand",
    "---",
    "title: {title_details$lib}",
    "subtitle: {title_details$version}",
    "format:",
    "  revealjs:",
    "    theme: {yaml$format$theme}",
    "    navigation-mode: vertical",
    "    self-contained: true",
    "---",
    .sep = "\n"
  )
  return(title_contents)
}
